import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "testando o Next Js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <div>
          <nav className="topnav">
            <div className="logo">Testando</div>
            <ul>
              <li><a href="../" className="active">Home</a></li>
              <li><a href="news">News</a></li>
              <li><a href="contact">Contact</a></li>
              <li><a href="login">Login</a></li>
            </ul>
          </nav>
        </div>

        {children}

      </body>
    </html>
  );
}
